print("Registration Form")
firstName = input("What is your first name?\n")
lastName = input("What is your last name?\n")
birthYear = int(input("What is your birth year?\n"))
print("")
print("First Name: " + firstName)
print("Last Name: " + lastName)
print("Birth Year: " + str(birthYear))
print("Welcome " + firstName + " " + lastName)
print("Your Registration is complete")
print("Your temporary password is: " + firstName + "*" + str(birthYear))
